version: '2'

services:
  bdb-driver:
    build:
      context: .
      dockerfile: ./compose/bigchaindb-driver-kyber/Dockerfile
    environment:
      BDB_HOST: bdb-server
      BIGCHAINDB_KEYPAIR_PUBLIC: GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4
    command: pytest -v

  rdb:
    image: rethinkdb
    ports:
      - "58585:8080"
      - "28015"

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - .:/etc/nginx/

  bdb-server:
    build:
      context: ./bigchaindb-server
      dockerfile: Dockerfile-dev
    volumes:
      - ./bigchaindb-server/bigchaindb:/usr/src/app/bigchaindb
      - ./bigchaindb-server/tests:/usr/src/app/tests
      - ./bigchaindb-server/docs:/usr/src/app/docs
      - ./bigchaindb-server/setup.py:/usr/src/app/setup.py
      - ./bigchaindb-server/setup.cfg:/usr/src/app/setup.cfg
      - ./bigchaindb-server/pytest.ini:/usr/src/app/pytest.ini
      - ./bigchaindb-server/tox.ini:/usr/src/app/tox.ini
      - ./bigchaindb-server/Makefile:/usr/src/app/Makefile
    environment:
      BIGCHAINDB_DATABASE_HOST: rdb
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_KEYPAIR_PUBLIC: GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4
      BIGCHAINDB_KEYPAIR_PRIVATE: 2kQgBtQnHoauw8QchKM7xYvEBW1QDoHzhBsCL9Vi1AzB
      BIGCHAINDB_CONSENSUS_PLUGIN: default
    ports:
      - "49984:9984"
    command: bigchaindb start

  bdb-server-plugins:
    build:
      context: .
      dockerfile:  ./compose/bdb-server-plugins/Dockerfile
    volumes:
      - ./bigchaindb-server/bigchaindb:/usr/src/app/bigchaindb
      - ./bigchaindb-server/tests:/usr/src/app/tests
      - ./bigchaindb-server/docs:/usr/src/app/docs
      - ./bigchaindb-server/setup.py:/usr/src/app/setup.py
      - ./bigchaindb-server/setup.cfg:/usr/src/app/setup.cfg
      - ./bigchaindb-server/pytest.ini:/usr/src/app/pytest.ini
      - ./bigchaindb-server/tox.ini:/usr/src/app/tox.ini
      - ./bigchaindb-server/Makefile:/usr/src/app/Makefile
    environment:
      BIGCHAINDB_DATABASE_HOST: rdb
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_KEYPAIR_PUBLIC: GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4
      BIGCHAINDB_KEYPAIR_PRIVATE: 2kQgBtQnHoauw8QchKM7xYvEBW1QDoHzhBsCL9Vi1AzB
      BIGCHAINDB_CONSENSUS_PLUGIN: consensus_asset_composition
    ports:
      - "49984:9984"
    command: bigchaindb start

  examples-client-frontend:
    build:
      context: .
      dockerfile: ./compose/examples-frontend/Dockerfile
    volumes:
      - ./examples/client/demo:/usr/src/app/examples/client/demo
      - ./examples/client/lib:/usr/src/app/examples/client/lib
      - ./examples/client/tx_explorer:/usr/src/app/examples/client/tx_explorer
      - ./examples/client/share_trader:/usr/src/app/examples/client/share_trader
      - ./examples/client/app_index_template.html:/usr/src/app/examples/client/app_index_template.html
      - ./examples/client/browserlist:/usr/src/app/examples/client/browserlist
      - ./examples/client/package.json:/usr/src/app/examples/client/package.json
      - ./examples/client/server.demo.js/:/usr/src/app/examples/client/server.demo.js
      - ./examples/client/webpack.config.js:/usr/src/app/examples/client/webpack.config.js
    environment:
      CLIENT_HOST: 0.0.0.0
      BDB_SERVER_URL: "http://localhost:49984"
      FLASK_HOST: "${DOCKER_MACHINE_IP}"
      FLASK_PORT: 48000
    ports:
      - "33000:3000"
    command: node server.demo.js

  examples-server-flask:
    build:
      context: .
      dockerfile: ./compose/examples-server/Dockerfile
    volumes:
      - ./examples/server:/usr/src/app/examples/server
    volumes_from:
      - bdb-server
    environment:
      BIGCHAINDB_DATABASE_HOST: rdb
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_KEYPAIR_PUBLIC: GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4
      BIGCHAINDB_KEYPAIR_PRIVATE: 2kQgBtQnHoauw8QchKM7xYvEBW1QDoHzhBsCL9Vi1AzB
      FLASK_HOST: 0.0.0.0
      DOCKER_MACHINE_IP: "${DOCKER_MACHINE_IP}"
    ports:
      - "48000:8000"
    command: python -m server.server_flask

  examples-server-tornado:
    build:
      context: .
      dockerfile: ./compose/examples-server/Dockerfile
    volumes_from:
      - examples-server-flask
    environment:
      BIGCHAINDB_DATABASE_HOST: rdb
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_KEYPAIR_PUBLIC: GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4
      BIGCHAINDB_KEYPAIR_PRIVATE: 2kQgBtQnHoauw8QchKM7xYvEBW1QDoHzhBsCL9Vi1AzB
      FLASK_HOST: 0.0.0.0
      TORNADO_HOST: 0.0.0.0
      DOCKER_MACHINE_IP: "${DOCKER_MACHINE_IP}"
    ports:
      - "48888:8888"
    command: python -m server.server_tornado

